export type AtsType =
  | "greenhouse"
  | "lever"
  | "personio"
  | "ashby"
  | "recruitee"
  | "smartrecruiters"
  | "amazon"
  | "custom";

export interface CompanyConfig {
  name: string;
  ats: AtsType;
  /** Slug on the ATS (e.g. "acme" in jobs.lever.co/acme). */
  id?: string;
  /** For personio: "de" (default) or "com". */
  tld?: string;
  /** For ats:"custom": the full careers page URL. */
  url?: string;
}

export type Source = "linkedin" | "stepstone" | "xing" | "indeed" | "career";

/** A raw posting, normalized across all sources. */
export interface RawJob {
  id: string;
  source: Source;
  /** Region label this came from (e.g. "Hessen"), if applicable. */
  region?: string;
  company: string;
  title: string;
  location: string;
  url: string;
  /** Posting date if the source provides one; null when unknown. */
  postedAt: string | null;
  /** Plain-text job description (HTML stripped). May be empty until enriched. */
  description: string;
}

/** Gemini's structured verdict on a single posting. */
export interface Analysis {
  matchScore: number; // 0–100
  recommend: "apply" | "maybe" | "skip";
  matchReason: string;
  salary: string | null;
  coverLetterNeeded: "yes" | "no" | "unknown";
  quickApply: "yes" | "no" | "unknown";
  remote: "onsite" | "hybrid" | "remote" | "unknown";
  employmentType: string;
  seniority: string;
  /** Primary language the job is conducted in, e.g. "German", "English". */
  language: string;
  /** 3–6 short helpful category tags, e.g. "React", "Remote", "Werkstudent". */
  tags: string[];
  keyRequirements: string[];
  redFlags: string[];
}

export interface AnalyzedJob extends RawJob {
  postedAtKnown: boolean;
  analysis: Analysis;
}

export type AppStatus =
  | "new"
  | "saved"
  | "applied"
  | "interviewing"
  | "offer"
  | "rejected"
  | "dismissed";

export const STATUS_ORDER: AppStatus[] = [
  "new",
  "saved",
  "applied",
  "interviewing",
  "offer",
  "rejected",
  "dismissed",
];

/** User-managed application state for a job. */
export interface JobState {
  status: AppStatus;
  notes: string;
  appliedAt: string | null;
  followUpAt: string | null;
  updatedAt: string;
}

/** A draft application generated by Gemini. */
export interface Draft {
  coverLetter: string;
  bullets: string[];
  shortMessage: string;
  language: string;
}

/** Everything persisted per job in data/jobs.json. */
export interface StoredJob {
  job: RawJob;
  analysis: Analysis | null;
  state: JobState;
  draft?: Draft | null;
  firstSeen: string;
  lastSeen: string;
}

export function defaultState(now: string): JobState {
  return { status: "new", notes: "", appliedAt: null, followUpAt: null, updatedAt: now };
}
